# Generated by Django 3.1.1 on 2020-10-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201010_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='carts',
            new_name='cart',
        ),
    ]
