# Generated by Django 3.1.1 on 2020-10-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201011_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
