# Generated by Django 3.1.1 on 2020-10-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20201031_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash', models.CharField(max_length=14)),
                ('nogod', models.CharField(max_length=14)),
                ('rocket', models.CharField(max_length=14)),
                ('ebl', models.CharField(max_length=15)),
                ('dbbl', models.CharField(max_length=15)),
            ],
        ),
    ]
