# Generated by Django 3.1.1 on 2020-10-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_paymentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='dbbl',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='ebl',
        ),
    ]
