# Generated by Django 3.1.1 on 2020-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20201101_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, default='yahoo'),
            preserve_default=False,
        ),
    ]
